package com.cryptomaster.model;

public enum CandlePattern {
    DOJI, HAMMER, SHOOTING_STAR,
    BULLISH_ENGULFING, BEARISH_ENGULFING,
    MORNING_STAR, EVENING_STAR,
    THREE_WHITE_SOLDIERS, THREE_BLACK_CROWS,
    PIERCING_LINE, DARK_CLOUD_COVER,
    HARAMI_BULLISH, HARAMI_BEARISH
}